require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/indicacoes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Indicacao. As you add validations to Indicacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Indicacao.create! valid_attributes
      get indicacoes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      indicacao = Indicacao.create! valid_attributes
      get indicacao_url(indicacao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_indicacao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      indicacao = Indicacao.create! valid_attributes
      get edit_indicacao_url(indicacao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Indicacao" do
        expect {
          post indicacoes_url, params: { indicacao: valid_attributes }
        }.to change(Indicacao, :count).by(1)
      end

      it "redirects to the created indicacao" do
        post indicacoes_url, params: { indicacao: valid_attributes }
        expect(response).to redirect_to(indicacao_url(Indicacao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Indicacao" do
        expect {
          post indicacoes_url, params: { indicacao: invalid_attributes }
        }.to change(Indicacao, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post indicacoes_url, params: { indicacao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested indicacao" do
        indicacao = Indicacao.create! valid_attributes
        patch indicacao_url(indicacao), params: { indicacao: new_attributes }
        indicacao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the indicacao" do
        indicacao = Indicacao.create! valid_attributes
        patch indicacao_url(indicacao), params: { indicacao: new_attributes }
        indicacao.reload
        expect(response).to redirect_to(indicacao_url(indicacao))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        indicacao = Indicacao.create! valid_attributes
        patch indicacao_url(indicacao), params: { indicacao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested indicacao" do
      indicacao = Indicacao.create! valid_attributes
      expect {
        delete indicacao_url(indicacao)
      }.to change(Indicacao, :count).by(-1)
    end

    it "redirects to the indicacoes list" do
      indicacao = Indicacao.create! valid_attributes
      delete indicacao_url(indicacao)
      expect(response).to redirect_to(indicacoes_url)
    end
  end
end
