require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/secretarias", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Secretaria. As you add validations to Secretaria, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Secretaria.create! valid_attributes
      get secretarias_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      secretaria = Secretaria.create! valid_attributes
      get secretaria_url(secretaria)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_secretaria_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      secretaria = Secretaria.create! valid_attributes
      get edit_secretaria_url(secretaria)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Secretaria" do
        expect {
          post secretarias_url, params: { secretaria: valid_attributes }
        }.to change(Secretaria, :count).by(1)
      end

      it "redirects to the created secretaria" do
        post secretarias_url, params: { secretaria: valid_attributes }
        expect(response).to redirect_to(secretaria_url(Secretaria.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Secretaria" do
        expect {
          post secretarias_url, params: { secretaria: invalid_attributes }
        }.to change(Secretaria, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post secretarias_url, params: { secretaria: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested secretaria" do
        secretaria = Secretaria.create! valid_attributes
        patch secretaria_url(secretaria), params: { secretaria: new_attributes }
        secretaria.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the secretaria" do
        secretaria = Secretaria.create! valid_attributes
        patch secretaria_url(secretaria), params: { secretaria: new_attributes }
        secretaria.reload
        expect(response).to redirect_to(secretaria_url(secretaria))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        secretaria = Secretaria.create! valid_attributes
        patch secretaria_url(secretaria), params: { secretaria: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested secretaria" do
      secretaria = Secretaria.create! valid_attributes
      expect {
        delete secretaria_url(secretaria)
      }.to change(Secretaria, :count).by(-1)
    end

    it "redirects to the secretarias list" do
      secretaria = Secretaria.create! valid_attributes
      delete secretaria_url(secretaria)
      expect(response).to redirect_to(secretarias_url)
    end
  end
end
