


class Curso < ApplicationRecord
    self.implicit_order_column = :created_at

    # extends ...................................................................

    # includes ..................................................................
    audited
    acts_as_paranoid

    include Searchrable

    # security (i.e. attr_accessible) ...........................................


    # relationships .............................................................

    # validations ...............................................................
    validates :nome, presence: true, uniqueness: { message: 'de curso já cadastrado' }
    # callbacks .................................................................
    # scopes ....................................................................
    default_scope -> { order(nome: :asc) }

    # additional config .........................................................
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
end
